// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwpK4SfvLOMI0rpPSswUdW1XYFMIXuJss',
    appId: '1:554019837516:web:9d520072e6f915d7f286e9',
    messagingSenderId: '554019837516',
    projectId: 'push-bung-7ca29',
    authDomain: 'push-bung-7ca29.firebaseapp.com',
    storageBucket: 'push-bung-7ca29.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK3rTwjVN3p4FJIK00baA8VxymeGPz16U',
    appId: '1:554019837516:android:dbab699987b71f26f286e9',
    messagingSenderId: '554019837516',
    projectId: 'push-bung-7ca29',
    storageBucket: 'push-bung-7ca29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRX4lTD_PeZJoNcUupDJrvRb5tajJN41E',
    appId: '1:554019837516:ios:a3c72da59ddfc2d3f286e9',
    messagingSenderId: '554019837516',
    projectId: 'push-bung-7ca29',
    storageBucket: 'push-bung-7ca29.firebasestorage.app',
    iosBundleId: 'com.example.pushBung',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRX4lTD_PeZJoNcUupDJrvRb5tajJN41E',
    appId: '1:554019837516:ios:a3c72da59ddfc2d3f286e9',
    messagingSenderId: '554019837516',
    projectId: 'push-bung-7ca29',
    storageBucket: 'push-bung-7ca29.firebasestorage.app',
    iosBundleId: 'com.example.pushBung',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwpK4SfvLOMI0rpPSswUdW1XYFMIXuJss',
    appId: '1:554019837516:web:5da05eff74491609f286e9',
    messagingSenderId: '554019837516',
    projectId: 'push-bung-7ca29',
    authDomain: 'push-bung-7ca29.firebaseapp.com',
    storageBucket: 'push-bung-7ca29.firebasestorage.app',
  );
}
