// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaJj6uVC_AAOci6-EoUUOQoW1jzUnV9s0',
    appId: '1:632612758944:web:5fa9f38697a04d107830c5',
    messagingSenderId: '632612758944',
    projectId: 'push-punny',
    authDomain: 'push-punny.firebaseapp.com',
    storageBucket: 'push-punny.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0pzKinpLE4uj8Eyf1k-v-MU-LuybB5qw',
    appId: '1:632612758944:android:1bff8ca7f16fbdeb7830c5',
    messagingSenderId: '632612758944',
    projectId: 'push-punny',
    storageBucket: 'push-punny.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDenlX7XG5XevOIiBLM2PH3Mz4qdSWJwCM',
    appId: '1:632612758944:ios:e1d7d217848d28d37830c5',
    messagingSenderId: '632612758944',
    projectId: 'push-punny',
    storageBucket: 'push-punny.firebasestorage.app',
    iosBundleId: 'com.example.pushBunny',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDenlX7XG5XevOIiBLM2PH3Mz4qdSWJwCM',
    appId: '1:632612758944:ios:e1d7d217848d28d37830c5',
    messagingSenderId: '632612758944',
    projectId: 'push-punny',
    storageBucket: 'push-punny.firebasestorage.app',
    iosBundleId: 'com.example.pushBunny',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaJj6uVC_AAOci6-EoUUOQoW1jzUnV9s0',
    appId: '1:632612758944:web:d107b422d2d196cc7830c5',
    messagingSenderId: '632612758944',
    projectId: 'push-punny',
    authDomain: 'push-punny.firebaseapp.com',
    storageBucket: 'push-punny.firebasestorage.app',
  );
}